---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fj9-cluster
  region: <eu-west-2>
  version: '<1.18>'

iam:
  withOIDC: true   

nodeGroups:
  - name: ng-1 
    instanceType: <t3.micro>
    desiredCapacity: 1
